export const UPDATE_ISSUERS = "UPDATE_ISSUERS";
export const LOAD_NEXT_PAGE_ISSUERS = "LOAD_NEXT_PAGE_ISSUERS";
export const LOAD_SUCCESS = "LOAD_SUCCESS";
export const LOAD_FAILURE = "LOAD_FAILURE";
export const UPDATE_ISSUER_STATE = "UPDATE_ISSUER_STATE";
export const SET_ISSUER = "SET_ISSUER";
