export const UPDATE_REGISTRY = "UPDATE_REGISTRY";
export const LOAD_NEXT_PAGE_REGISTRY = "LOAD_NEXT_PAGE_REGISTRY";
export const REGISTRY_LOAD_SUCCESS = "REGISTRY_LOAD_SUCCESS";
export const REGISTRY_LOAD_FAILURE = "REGISTRY_LOAD_FAILURE"
