export const UPDATE_REGISTRY = "UPDATE_REGISTRY";
export const LOAD_NEXT_PAGE_REGISTRY = "LOAD_NEXT_PAGE_REGISTRY";
export const REGISTRY_LOAD_SUCCESS = "REGISTRY_LOAD_SUCCESS";
export const REGISTRY_LOAD_FAILURE = "REGISTRY_LOAD_FAILURE"
export const SET_CONTRACT = "SET_CONTRACT";
export const CHANGE_ISSUER_STATE = "CHANGE_ISSUER_STATE";
export const ADD_TO_HASH = "ADD_TO_HASH";
